const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Eurika/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
const root=process.env.ERD_DOC_ROOT?path.resolve(process.env.ERD_DOC_ROOT):path.resolve(__dirname,'../..');
const model=require(path.join(root,'assets/erd/model.js'));
const expected=model.tables.flatMap(t=>t.fields.filter(f=>f.ref).map(f=>({parent:f.ref.table,key:f.ref.field,table:t.name,field:f.name,nullable:f.nullable,unique:!!f.unique})));
const pdfjs=process.env.PDFJS_ROOT||'C:/Users/Eurika/AppData/Local/npm-cache/_npx/7673eca99d5dbcb2/node_modules/pdfjs-dist';
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname==='/pdf-review')return res.writeHead(200,{'Content-Type':'text/html'}).end('<html><body></body></html>');const directory=url.pathname.startsWith('/pdfjs/')?pdfjs:root,suffix=url.pathname.startsWith('/pdfjs/')?url.pathname.slice(6):url.pathname,file=path.resolve(directory,'.'+suffix);if(!file.startsWith(path.resolve(directory)+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.pdf':'application/pdf'})[path.extname(file)]||'application/octet-stream'}).end(data);});});
(async()=>{let browser;await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;
for(const name of ['ERD.html','ERD-A4.html','ERD-PRINT.html']){
 await page.goto(base+'/'+name);await page.waitForFunction(()=>window.__erdReady);assert.equal(await page.locator('.erd-sheet').count(),1);assert.equal(await page.locator('[data-table]').count(),model.tables.length);assert.equal(await page.locator('[data-field]').count(),model.tables.reduce((n,t)=>n+t.fields.length,0));assert.equal(await page.locator('[data-relation]').count(),expected.length);assert.equal(await page.locator('[data-cardinality]').count(),expected.length*2);
 assert.equal(await page.locator('[data-cardinality] text').count(),0,'Use Crow\'s Foot symbols without numeric labels');
 const result=await page.evaluate(()=>{
  const issues=[],svg=document.querySelector('.erd-sheet svg'),g=window.ErdGeometry.complete;
  const overlaps=(a,b,pad=.2)=>Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)>pad&&Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)>pad;
  for(const table of svg.querySelectorAll('[data-table]')){const rect=table.querySelector('rect'),r={x:+rect.getAttribute('x'),y:+rect.getAttribute('y'),width:+rect.getAttribute('width'),height:+rect.getAttribute('height')};const texts=[...table.querySelectorAll('text')];for(const t of texts){const b=t.getBBox();if(b.x<r.x+.5||b.x+b.width>r.x+r.width-.5||b.y<r.y||b.y+b.height>r.y+r.height)issues.push('Clipped table text: '+table.dataset.table+'.'+t.textContent);}for(let i=0;i<texts.length;i++)for(let j=i+1;j<texts.length;j++)if(overlaps(texts[i].getBBox(),texts[j].getBBox()))issues.push('Overlapping text: '+texts[i].textContent+' / '+texts[j].textContent);}
  for(let i=0;i<g.nodes.length;i++)for(let j=i+1;j<g.nodes.length;j++){const a=g.nodes[i],b=g.nodes[j];if(overlaps({x:a.x,y:a.y,width:a.w,height:a.h},{x:b.x,y:b.y,width:b.w,height:b.h}))issues.push('Overlapping tables: '+a.name+' / '+b.name);}
  for(const link of g.paths)for(let i=1;i<link.points.length;i++){const a=link.points[i-1],b=link.points[i];if(a[0]!==b[0]&&a[1]!==b[1])issues.push('Non-orthogonal connector: '+link.id);for(const n of g.nodes){const hit=a[0]===b[0]?a[0]>n.x+.2&&a[0]<n.x+n.w-.2&&Math.max(a[1],b[1])>n.y+.2&&Math.min(a[1],b[1])<n.y+n.h-.2:a[1]>n.y+.2&&a[1]<n.y+n.h-.2&&Math.max(a[0],b[0])>n.x+.2&&Math.min(a[0],b[0])<n.x+n.w-.2;if(hit)issues.push('Connector crosses a table: '+link.id+' / '+n.name);}}
  for(const t of svg.querySelectorAll('text')){const b=t.getBBox();if(b.x<0||b.y<0||b.x+b.width>1980||b.y+b.height>2800)issues.push('Outside page: '+t.textContent);}
  return {issues,relations:window.ErdRelations.map(r=>({parent:r.parent,key:r.key,table:r.table,field:r.field,nullable:r.optional,unique:r.one}))};
 });assert.deepEqual(result.issues,[],'All fields readable; connectors avoid table interiors');assert.deepEqual(result.relations,expected);
 await page.locator('[data-cardinality]').first().focus();assert(await page.locator('svg[data-active-relation]').count());await page.keyboard.press('Escape');assert.equal(await page.locator('svg[data-active-relation]').count(),0);await page.getByRole('combobox').selectOption('2');assert.equal(await page.locator('.erd-sheet').evaluate(e=>getComputedStyle(e).getPropertyValue('--erd-zoom').trim()),'2');
}
await page.goto(base+'/pdf-review');const pdf=await page.evaluate(async()=>{const js=await import('/pdfjs/build/pdf.mjs');js.GlobalWorkerOptions.workerSrc='/pdfjs/build/pdf.worker.mjs';const document=await js.getDocument({url:'/assets/erd/erd-a4.pdf',standardFontDataUrl:'/pdfjs/standard_fonts/'}).promise;const page=await document.getPage(1),items=(await page.getTextContent()).items;return{pages:document.numPages,dimensions:page.view,text:items.map(i=>i.str).join(' '),items:items.filter(i=>i.str.trim()).map(i=>({text:i.str,x:i.transform[4],y:i.transform[5],width:i.width}))};});assert.equal(pdf.pages,1,'Actual PDF is exactly one page');assert(Math.abs(pdf.dimensions[2]-595.28)<1&&Math.abs(pdf.dimensions[3]-841.89)<1,'Actual PDF is portrait A4');for(const table of model.tables){assert(pdf.text.includes(table.name));for(const field of table.fields)assert(pdf.text.includes(field.name));}for(const item of pdf.items)assert(item.x>3&&item.x+item.width<592&&item.y>3&&item.y<839,'PDF text is inside A4 bounds: '+item.text);
assert(!pdf.items.some(item=>/^(?:1|0\.\.1|0\.\.\*)$/.test(item.text.trim())),'PDF has no numeric cardinality labels');
await page.evaluate(async()=>{const js=await import('/pdfjs/build/pdf.mjs');const doc=await js.getDocument({url:'/assets/erd/erd-a4.pdf',standardFontDataUrl:'/pdfjs/standard_fonts/'}).promise;const pdfPage=await doc.getPage(1),viewport=pdfPage.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.id='erd-pdf-preview';canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);document.body.style.margin='0';document.body.append(canvas);await pdfPage.render({canvasContext:canvas.getContext('2d'),viewport}).promise;await doc.destroy();});
const qa=path.join(root,'tmp/pdfs/erd-symbols-a4.png');fs.mkdirSync(path.dirname(qa),{recursive:true});await page.locator('#erd-pdf-preview').screenshot({path:qa});
assert.deepEqual(errors,[]);console.log('Verified actual one-page portrait A4 PDF and all 3 viewers: 30 tables, 208 fields, 61 orthogonal relationships, 122 cardinality markers, no numeric cardinality labels, no text overlap or connector-through-table defects; zoom and keyboard tracing work.');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);process.exitCode=1;});
